
services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
      - ./uploads:/code/uploads
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  resize_worker:
    build: .
    command: python app/worker/resize/worker.py
    depends_on:
      - rabbitmq

  watermark_worker:
    build: .
    command: python app/worker/watermark/worker.py
    depends_on:
      - rabbitmq

  detect_worker:
    build: .
    command: python app/worker/detect/worker.py
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
